### ISSUE TITLE
Able to steal funds

### ISSUE THREAD

**Issue by NickErrant** [gitcoinco/smart_contracts#5]
When bounty is denominated in ether, only validation on the amount field when a bounty is created is `require(_amount >= msg.value);`
https://github.com/gitcoinco/smart_contracts/blob/9100e1cfde32fcc7a45ec5cfbc11df5bf8d36699/contracts/bounty/BountyIndex.sol#L75

Attacker could post bounty where _amount is greater than msg.value, but lower than the balance of the contract, then claim/approve said bounty for themselves. This would effectively steal the difference between _amount - msg.value.

Suggested fix:
When bounty is denominated in ether, set amount for that bounty equal to msg.value

**Comment by owocki** [comment]
f33510fbb6677961b53c2a249705289815fb1753

**Comment by owocki** [comment]
migrating contract now.

**Comment by owocki** [comment]
just sent you a tip for submitting this.  thanks @NickErrant !

**Comment by NickErrant** [comment]
Received bounty payment :)
